language: python
python:
    - "2.7"

install:
  - pip install numpy
  - pip install matplotlib
  # install TensorFlow from https://storage.googleapis.com/tensorflow/
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.4" ]]; then
      pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl;
    fi
  - "pip install -r requirements.txt"
  - python setup.py install

script:
  - py.test -v --cov-report term-missing --cov timeflow

after_success:
  - coveralls
